### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by DoktorHibiskus** [spajus/tank_island#4]
**Hi Spajus!** 
Thank you for this great game! But for me it's not working. I tried to install it according to you,
but it says:

_/var/lib/gems/2.7.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer/tileset.rb:12:in `read': no implicit conversion of GameWindow into String (TypeError)_

Do you have a clue?
With dear greetings
_Hibiscus_

**Comment by spajus** [comment]
Hey, thank you for reporting! I made a mistake of not locking the dependencies when I created this, so newer dependencies changed the API. I'll find some time to fix this in following days.
Happy holidays!

**Comment by DoktorHibiskus** [comment]
Hi, thank you so much! Have a happy new years eve and happy holidays!

**Comment by Willardgmoore** [comment]
I'm starting to look into this. Trying to figure out which versions I need for things right now based on this message or if I just need to update the depreciation issue?

```
fs=1 w=1200 h=800 tank_island
DEPRECATION WARNING: Passing a Window to Image.from_text has been deprecated in Gosu 0.9 and this method now uses an options hash, see https://www.libgosu.org/rdoc/Gosu/Image.html ,

#Called from ["/Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/menu_state.rb:7:in `initialize'"].
DEPRECATION WARNING: Passing a Window to Song#initialize has been deprecated in Gosu 0.7.17.,

#Called from ["/Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/menu_state.rb:23:in `new'"].
DEPRECATION WARNING: Passing a Window to Image.from_text has been deprecated in Gosu 0.9 and this method now uses an options hash, see https://www.libgosu.org/rdoc/Gosu/Image.html ,

#Called from ["/Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/menu_state.rb:30:in `update'"].
DEPRECATION WARNING: Passing a Window to Image#initialize has been deprecated in Gosu 0.9 and this method now uses an options hash, see https://www.libgosu.org/rdoc/Gosu/Image.html ,

#Called from ["/Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/map.rb:87:in `new'"].
/Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer/tileset.rb:12:in `read': no implicit conversion of GameWindow into String (TypeError)
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer/tileset.rb:12:in `initialize'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer/tileset.rb:7:in `new'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer/tileset.rb:7:in `load_json'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu_texture_packer-0.1.8/lib/gosu_texture_packer.rb:8:in `load_json'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/components/tree_graphics.rb:66:in `trees'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/components/tree_graphics.rb:52:in `load_sprite'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/components/tree_graphics.rb:7:in `initialize'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/tree.rb:6:in `new'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/tree.rb:6:in `initialize'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/map.rb:119:in `new'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/map.rb:119:in `generate_trees'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/entities/map.rb:19:in `initialize'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/play_state.rb:9:in `new'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/play_state.rb:9:in `initialize'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/menu_state.rb:52:in `new'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/game_states/menu_state.rb:52:in `button_down'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/lib/misc/game_window.rb:28:in `button_down'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu-1.2.0/lib/gosu/patches.rb:64:in `tick'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/gosu-1.2.0/lib/gosu/patches.rb:64:in `tick'
	from /Users/admin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tank_island-1.0.5/bin/tank_island:82:in `<top (required)>'
	from /Users/admin/.rbenv/versions/3.0.1/bin/tank_island:23:in `load'
	from /Users/admin/.rbenv/versions/3.0.1/bin/tank_island:23:in `<main>'
```

**Comment by Willardgmoore** [comment]
I looked back through the Gosu versions and figured out which one is the right version. I'll make a PR.

**Comment by Willardgmoore** [comment]
This issue is solved by the recent merge.
